### ISSUE TITLE
Feral Crawler

### ISSUE THREAD

**Issue by Canute00** [hamzahiary/ApocalypseModA19.2#1]
Hi,
at a new game at day 1 a feral crawler chase me through the woods.
But he wasn't crawling he was running like a ghost hovering over the ground.

**Comment by hamzahiary** [comment]
Hi Canute00
I will release an update this week to fix few issue
One of them the feral crawler running speed and spwan rate 
Hunt : I changed the crawler Zombie walk type , that's why you see him floating
